name: teleportScroll
version: '${project.version}'
main: com.github.kamida.teleportscroll.teleportScroll
api-version: 1.19
authors: [ Kamida ]
description: Craftable scroll that when used, teleports the user to their bed or spawn.

commands:
  telescroll:
    description: Gives the player a scroll
    usage: /telescroll give <amount>