name: teleportScroll
version: '${project.version}'
main: com.github.kamida.teleportscroll.teleportScroll
api-version: 1.19
authors: [ Kamida ]
description: Craftable scroll that when used, teleports the user to their bed or spawn.

commands:
  telescroll:
    description: Gives the player a scroll
    usage: /telescroll help

permissions:
  telescroll.give:
    description: Allows the player to use /telescroll give <amount>
    default: op
  telescroll.craft:
    description: Allows player to craft the teleport scroll
    default: not op